Goodhands
hngi/expenseng pull request #77
Opened 2020-07-07 20:25 UTC by charleyvibez

2020-07-07 22:03 UTC, goodhands requested changes
Good work, kindly update the model names accordingly. Thanks.

2020-07-07 22:03 UTC, goodhands commented on app/Budget_spending.php
> +class Budget_spending extends Model
Change this Expense, the table is now expense

Also not for future case that a naming convention for model names is: BudgetSpending, instead of underscore.

2020-07-07 22:03 UTC, goodhands commented on app/Cabinets.php
> +class Cabinets extends Model
Change this to singular. All model names should be singualar.

`Cabinet`

2020-07-07 22:03 UTC, goodhands commented on app/Daily_payments.php
> +class Daily_payments extends Model
Change this to `Payment`

2020-07-07 22:03 UTC, goodhands commented on app/Ministries.php
> +class Ministries extends Model
Ministry

2020-07-07 22:03 UTC, goodhands commented on app/Sectors.php
> +class Sectors extends Model
`Sector`

2020-07-07 22:03 UTC, goodhands commented on database/factories/BudgetFactory.php
> +        'classification' => $faker->firstName
try using `array_rand(['Economic', 'administrative', 'Functions of Govt'])` instead of `$faker->firstName` for **classification**

2020-07-07 22:03 UTC, goodhands commented on database/factories/BudgetSpendingFactory.php
> +$factory->define(Budget_spending::class, function (Faker $faker) {
Change this class to Expense

2020-07-07 22:03 UTC, goodhands commented on database/factories/CabinetsFactory.php
> +$factory->define(Cabinets::class, function (Faker $faker) {
Cabinet

2020-07-07 22:03 UTC, goodhands commented on database/factories/DailyPaymentsFactory.php
> +$factory->define(Daily_payments::class, function (Faker $faker) {
Payment

2020-07-07 22:03 UTC, goodhands commented on database/factories/MinistriesFactory.php
> +$factory->define(Ministries::class, function (Faker $faker) {
Ministry

2020-07-07 22:03 UTC, goodhands commented on database/factories/SectorsFactory.php
> +$factory->define(Sectors::class, function (Faker $faker) {
Sector

2020-07-08 07:59 UTC, charleyvibez commented
@goodhands I have updated it now

2020-07-08 09:39 UTC, merged